### ISSUE TITLE
It should be installed `classnames` package

### ISSUE THREAD

**Issue by synuns** [mondaycom/storybook-addon-playground#38]
`storybook-addon-playground` need to install the `classnames` package, can you please remove this dependency and deploy it?

```shell
✘ [ERROR] Could not resolve "classnames"

    node_modules/storybook-addon-playground/dist/components/Editor/EditorTab.js:3:15:
      3 │ import cx from 'classnames';
        ╵                ~~~~~~~~~~~~

  You can mark the path "classnames" as external to exclude it from the bundle, which will remove
  this error.
```

**Comment by YossiSaadi** [comment]
Hey @synuns, @joulss
sorry for that
will make it a dep instead of devDep
did you had issues with more packages other than `classnames`?

**Comment by Joulss** [comment]
> Hey @synuns, @Joulss sorry for that will make it a dep instead of devDep did you had issues with more packages other than `classnames`?

I don't believe so, but I should try the installation again to confirm.
