### ISSUE TITLE
Feature: Option to Disable Playground for Certain Stories

### ISSUE THREAD

**Issue by k-borley** [mondaycom/storybook-addon-playground#56]
Is it possible to disable the playground addon for certain stories? I'd like it to only show up on the Playground story I created, but currently it shows up in all of them. Maybe a parameter option to disable playground on a per-story basis?

**Comment by YossiSaadi** [comment]
Hey again @k-borley !
I'm not sure I fully understood what you need
You want the bottom panel to not show for stories except for the Playground story?

If so, unfortunately Storybook does not allow it, we have tried it.

We do plan in a near-future update to make the Playground a story-based, which means that every Story page you'll go into will include this story as a source point, and when you'll edit the editor content it will change for the specific story you're in.

**Comment by k-borley** [comment]
Ah okay thanks for explaining. A story-based playground would be amazing, I'll keep an eye out for that update. Thank you!

**Comment by planetmalone** [comment]
Hi! Thanks for this addon. Is there any timeline on when the story-based Playground will be ready?

**Comment by YossiSaadi** [comment]
> Hi! Thanks for this addon. Is there any timeline on when the story-based Playground will be ready?

Hey @planetmalone, I'm hoping somewhere in next one-two months
